services:
  - type: web
    name: translate-fairy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false # você define a chave manualmente no painel do Render
    autoDeploy: true
